### ISSUE TITLE
checkPayment

### ISSUE THREAD

**Issue by nayuta-ueno** [breez/lspd#1]
[checkPayment()](https://github.com/breez/lspd/blob/7291d535ee7b4e2e9f40dee394a373dd73cee7da/intercept.go#L29) uses `incomingAmountMsat` to calculate fee.
[breez](https://github.com/breez/breez/blob/5e07746cddd77d4f75f4176c3f1edc0c56101973/account/payments.go#L510) calculate fee using user requested amount.
So I thought that the lspd fee check would use `outgoingAmountMsat` instead of `incomingAmountMsat`.

```
                       +------+                       +-------+
--incomingAmountMsat-->| lspd |--outgoingAmountMsat-->| breez |
                       +------+                       +-------+


lspd_fee = incomingAmountMsat - outgoingAmountMsat?
```

**Comment by yaslama** [comment]
> [breez](https://github.com/breez/breez/blob/5e07746cddd77d4f75f4176c3f1edc0c56101973/account/payments.go#L510) calculate fee using user requested amount.

Here also, the fee is calculated from `amountMsat` which is the amount paid by the payer (called `incomingAmountMsat` in lspd)

**Comment by nayuta-ueno** [comment]
Thanks for the reply.

I figured that the fee for 1,000,000 sats would be calculated like this.
Is the parameter for PaymentInformation wrong?

```
breez
  request: 1,000,000 sats
  fee: 1,000,000 sats x 0.4% = 4,000 sats
  PaymentInformation:
    IncomingAmountMsat: 1,004,000 sats
    OutgoingAmountMsat: 1,000,000 sats

   ↓↓↓

lspd
  checkPayment(1,004,000, 1,000,000)
    fees := 1,004,000 * 40 / 10_000 / 1_000 * 1_000 = 4,016 sats
```

**Comment by yaslama** [comment]
The fees are currently deducted from the amount the payer pays (and the payer receives the paid amount minus the fees) because the fact that the payee needs to open a channel doesn't have to change the amount paid by the payer. It's not "his fault". Do you have a reason to prefer the fees to be added to the original amount?

**Comment by nayuta-ueno** [comment]
I was mistaken...
I was asking the question simply because I thought it would "add" to my commission.
Thank you.
