### ISSUE TITLE
Incompatlble binaries: GLIBC version

### ISSUE THREAD

**Issue by darioAnongba** [breez/lspd#205]
Hi guys,

I've been in the process of deploying a LSP infrastructure on a Kubernetes cluster and I'm now adding `lspd` as a CLN plugin and running into issues. I'm currently downloading the `lspd-v24.03.16-linux-amd64.tar.gz` binaries and expecting to run them in a `elementsproject/lightningd:v24.02-amd64` image. I'm not building from source. 

## Error

```
2024-03-20T17:23:15.738Z DEBUG   plugin-manager: started(30) /root/.lightning/plugins/lspd_cln_plugin
/root/.lightning/plugins/lspd_cln_plugin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /root/.lightning/plugins/lspd_cln_plugin)
/root/.lightning/plugins/lspd_cln_plugin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /root/.lightning/plugins/lspd_cln_plugin)
lightningd: FATAL SIGNAL 11 (version v24.02)
0x555f2dac6070 send_backtrace
	common/daemon.c:33
0x555f2dac60f8 crashdump
	common/daemon.c:75
0x7fe2213c713f ???
...
```

## Cause

`lspd_cln_plugin` is a CLN plugin, it should be built in a way that works with CLN. Is it working for you? Maybe the versions I'm trying to use are not compatible?

**Comment by JssDWt** [comment]
Fixed for the next release in https://github.com/breez/lspd/pull/206
