### ISSUE TITLE
lspd doesn't exit

### ISSUE THREAD

**Issue by JssDWt** [breez/lspd#45]
The lspd process is not cleaned up by the integration tests, because it doesn't exit. It appears to be stuck in the grpc 'Recv'. This should be cancelled when `interceptor.Stop` is called. It appears `interceptor.Stop` is not called, because the stop signal is not intercepted properly.

**Comment by roeierez** [comment]
@yaslama we need your feedback here if you can cleanly shutdown LSPD in your live environment.
