### ISSUE TITLE
Possibly unhandled htlcs in cln lspd when lspd stops

### ISSUE THREAD

**Issue by JssDWt** [breez/lspd#48]
When the cln lspd stops while a htlc is being handled, there is a gap.
- Either lspd will keep receiving new htlcs and is also able to send.
- Or lspd will stop receiving htlcs but is also unable to send.

So in either case there could be htlcs unhandled.
Solutions could be:
- Replay unhandled htlcs that were already sent from the cln plugin when the lspd drops out.
- Make a different stream for receiving htlc_accepted and the htlc resolutions. This way the receiving context could be cancelled first, then the remaining htlcs could be sent out and then the sending context can be cancelled.

**Comment by roeierez** [comment]
> * Make a different stream for receiving htlc_accepted and the htlc resolutions. This way the receiving context could be cancelled first, then the remaining htlcs could be sent out and then the sending context can be cancelled.

If you find a clean way to signal the plugin to stop sending htlcs we could implement this strategy without duplicating the stream.

**Comment by JssDWt** [comment]
> If you find a clean way to signal the plugin to stop sending htlcs we could implement this strategy without duplicating the stream.

I think the best answer is keeping track of which htlcs were sent but not handled yet and replay those when there is a new subscriber. The default replay mechanism of CLN only works when the CLN node is restarted, so there has to be another mechanism to replay unhandled htlcs when lspd is restarted.
